### ISSUE TITLE
Forbidigo appears to ignore test files entirely

### ISSUE THREAD

**Issue by extemporalgenome** [ashanbrown/forbidigo#16]
I am unable to get forbidigo to match anything on `*_test.go` files. For example, the following has no linter output:

```sh
git clone https://github.com/ashanbrown/forbidigo
go install
forbidigo assert -- ./...
```

However, the following does have linter output:

```sh
git clone https://github.com/ashanbrown/forbidigo
go install
forbidigo parse -- ./...
```

The same applies with forbidigo linter within golangci-lint.

`-exclude_godoc_examples=false` appears to have no effect either.

Is this an intentional (and undocumented) design decision?

**Comment by ashanbrown** [comment]
Thanks for teh report @extemporalgenome .  I agree, it looks like it wasn't including tests by default.  I've made including tests the new default in #17 and added an option to exclude.  This was intended but admittedly I always use golangci-lint to run this linter and it ends up deciding whether tests are included or not.  In general, you're likely to benefit from the fine-grained exception configuration that golangci-lint offers.  I chose not to try to reproduce it all in the standalone command.

I think the issue you described with `-exclude_godoc_examples=false` not having the desired effect may be due to your test example not being in a test file (which obviously wasn't covered because of the first issue).  I'm not 100% sure about this, but I believe the `Example` prefix is only meaningful in tests and this linter only checks for this prefix in tests.
