### ISSUE TITLE
Regression in v1.6.0

### ISSUE THREAD

**Issue by marselester** [ashanbrown/forbidigo#41]
Hi! Could you please advice on how to forbid the following pattern `[Uu]ser[iI][dD]`? Here is a failing test.

```go
func TestForbiddenUserID(t *testing.T) {
	linter, _ := NewLinter([]string{`[Uu]ser[iI][dD]`})
	expectIssues(t, linter, false, `
package bar
type UserID string
`, "use of `UserID` forbidden by pattern `[Uu]ser[iI][dD]` at testing.go:3:6")
}

// Expected: [use of `UserID` forbidden by pattern `[Uu]ser[iI][dD]` at testing.go:3:6]
// Got: []
```

This test passes in v1.5.3.

**Comment by atom-andrew** [comment]
@marselester Thanks for this report and for reporting this use case.  Per https://github.com/ashanbrown/forbidigo/pull/40, I think this regression was intentional (it pretty much matches exactly the description of that PR).   My understanding is that we can forbid use of `UserID` but we can't forbid the definition.  Could you tell me more about the use case?  The original goal of forbidigo was to prohibit "use" of identifiers rather than limiting what strings you could include in the names, so while I agree this was a regression, it's not really a change in how the tool was intended to be used.

**Comment by marselester** [comment]
Thank you for the clarification. The use case is to prohibit use of deprecated names in a codebase.

**Comment by ashanbrown** [comment]
That use case might fall in the domain of a "naming convention" linter, although I'm not aware of one for golang.
