### ISSUE TITLE
What about os.IsExist, os.IsNotExist, os.IsPermission

### ISSUE THREAD

**Issue by quite** [ashanbrown/forbidigo#48]
Did you consider forbidding `os.IsExist`, `os.IsNotExist`, and `os.IsPermission`, for which the docs says that `errors.Is` should be used? (there may also be other on this pattern).

**Comment by ashanbrown** [comment]
That's an interesting use case.  It looks like those may not have been offically deprecated (otherwise something like https://staticcheck.dev/docs/checks#SA1019) might find them.  The default set of exclusions is mainly an example.  Also, changing it could break a lot of code that's out there, so I'm inclined to leave it as is for now.  I would generally say that the use case of handling deprecations might not be ideal for this tool, since it might, for example, depend on the version of "go" that you are using.
