### ISSUE TITLE
Issues with permit in golangci-lint context

### ISSUE THREAD

**Issue by bnweiss** [ashanbrown/forbidigo#9]
I'm not sure what the disconnect here is but golangci-lint still displays this usage of permit as an error.
![image](https://user-images.githubusercontent.com/42150273/134210412-d67bf4a9-59b5-493c-91db-159e4d37fa3f.png)

**Comment by ashanbrown** [comment]
Hi @bnweiss , thanks for the report.  Inside golangci-lint, we only allow the `//nolint` directives and disable `//permit`.  This is because these directives are hard to implement correctly and also because golangci-lint has features that I recommend (and worked on) such as ensuring that there is an explanation accompanying each directive and that each directive is actually in-use.  Please try `//nolint` and if there is still a problem, please let me know.  I've also updated the readme to make this clearer.
